### ISSUE TITLE
anticipated changes needed for webpack v4 support?

### ISSUE THREAD

**Issue by thescientist13** [anthonygore/html-critical-webpack-plugin#9]
I'm in the process of upgrading to `webpack@4.0.0` and while working through issues with `ExtractTexxtWebpackPlugn` which I think is why I am seeing this error in [my PR here]()
```shell
(node:15301) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:15301) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
Error: css should not be empty
    at /Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/penthouse/lib/index.js:308:33
    at Generator.next (<anonymous>)
    at step (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/penthouse/lib/index.js:45:191)
    at /Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/penthouse/lib/index.js:45:437
    at new Promise (<anonymous>)
    at /Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/penthouse/lib/index.js:45:99
    at Promise (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/penthouse/lib/index.js:325:20)
    at new Promise (<anonymous>)
    at module.exports (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/penthouse/lib/index.js:269:10)
    at /Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/critical/lib/core.js:170:16
    at tryCatcher (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:454:14)
    at ReductionPromiseArray._resolve (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/reduce.js:61:19)
    at ReductionPromiseArray._resolveEmptyArray (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/reduce.js:52:10)
    at ReductionPromiseArray.init (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise_array.js:71:18)
    at Promise._settlePromise (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
✨  Done in 21.65s.
```

and so just wanted to start the discussion to see if any of the breaking changes for plugins in v4 would apply here?
https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

Maybe the removal of `this.options`?   If help is needed, I can try and take a shot at it.  Thanks for this great plugin!  🙏 ✌️

**Comment by anthonygore** [comment]
Hey @thescientist13, sorry for the late reply. Have you made any progress on upgrading to v4?

**Comment by thescientist13** [comment]
Hey @anthonygore !  I am still getting there piece by piece [here](https://github.com/ProvidenceGeeks/website-frontend/pull/142) but now that #10 has been merged (thank you!), I can just try updating webpack here in this repo and see if all the tests still pass. ✅

**Comment by lili21** [comment]
it's extract-text-webpack-plugin's [issue](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/738)

**Comment by bfkeinberg** [comment]
It appears that for webpack v4 extract-text-webpack-plugin is dead and mini-css-extract-plugin is the paved road approach.

**Comment by thescientist13** [comment]
@lili21 / @bfkeinberg 
Yeah, that seems like the general consensus of the community from what I've been seeing.  I think the big thing waiting from **mini-css-extract-plugin** (for me anyway at the time) was `[contenthash]` support (https://github.com/webpack-contrib/mini-css-extract-plugin/issues/1)  which seems to have landed.  

@anthonygore 
So, In the case of this plugin, since it only ever expected / assumed **extract-text-webpack-plugin** as a `peerDependency`, it seems like it is a safe bet to say that for the case of webpack v4 support, this plugin should steer in the direction of webpack itself, which is moving to native CSS bundling support.  (**mini-css-extract-plugin** is only a stopgap to that eventuality).

I am going to test out **mini-css-extract-plugin** now in my side project and see it how it goes, mainly to make sure bundle sizes are comparable to that of **extract-text-webpack-plugin**.  Will report back.

**Comment by thescientist13** [comment]
Seems to be working well for me with **mini-css-extract-plugin** based on my work in my project (https://github.com/ProvidenceGeeks/website-frontend/pull/142).

**Comment by anthonygore** [comment]
Yeah, I think you're right about **mini-css-extract-plugin** being the future. However, I think we proceed with **extract-text-webpack-plugin** for now, though, and wait and see where the dust settles. Do you agree?

**Comment by thescientist13** [comment]
@anthonygore [these comments](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701#issuecomment-374551300) seem to suggest ETWP will not be making the jump to full webpackv4 support

**Comment by thescientist13** [comment]
So I think the issue may be related to Chrome Headless dependency.  Switched the CircleCI build to use my [personal Docker image]() that has Chrome Headless installed and now [the build is passing](https://circleci.com/gh/thescientist13/html-critical-webpack-plugin/8)

Maybe the dependency is coming from JSDOM?  Let me see if I can dig further into where that dependency is coming from since I think it would ideal if we could get by without it due to the complex nature of setting up environments (local, CI, etc) to support it.

**Comment by anthonygore** [comment]
Interesting. Any ideas as to why this issue only happens when testing?

**Comment by thescientist13** [comment]
not sure @anthonygore , but I will do some more testing today on this and hopefully get a straight answer as to what's the issue.

**Comment by thescientist13** [comment]
FWIW I see similar output in my project too
https://circleci.com/gh/ProvidenceGeeks/website-frontend/327
```shell
(node:839) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:839) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
(node:839) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
/home/circleci/repo/node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

(node:839) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

In this case, the build is not exiting too, which is similar to the behavior we're seeing here and so has probably been doing so for all my PRs. 

So basically using critical [as of version 1.0.0](https://github.com/addyosmani/critical/releases/tag/v1.0.0) is dependent on runtime environment that has support for Headless Chrome, and more to the point, the OS specific libraries needed to run it.

When this package [was bumped to that version](https://github.com/addyosmani/critical/releases/tag/v1.0.0), my guess is that is when things started silently breaking for people 😞 

And so in my PR above, it included a bump to this latest version of **html-critical-webpack-plugin**.


So next steps I see are basically around documentation / maintenance / tracking:
1. I will open an issue tracking this breaking change in **html-critical-webpack-plugin**
1. I will open a PR to demonstrate outside of the unit testing context (using CircleCI to demonstrate) build failures
1. I will bump my [docker container](https://github.com/thegreenhouseio/docker-nodejs-dev#features) to support LTS version of NodeJS 8.9.4
1. I will update the PR to use the new version of the docker container as then the build should then pass.  This would be a good time to document needing a build / development environment that has support for Headless Chrome, i.e. [puppeteer](https://github.com/GoogleChrome/puppeteer)
1. We merge that PR
1. I rebase that into the unit testing PR (which should then pass and do all the things)
1. We can then release a new version of **html-critical-webpack-plugin**

Thoughts?
